### ISSUE TITLE
Tree:value relation to hydra:member data in a node is undefined 

### ISSUE THREAD

**Issue by Lamasaurus** [pietercolpaert/TreeOntology#3]
Each tree:node has a tree:value which defines a value for that node to decent the tree on. For example the value "T": 
```
{
        "@type": "tree:Node",
        "tree:value": "T",

	"hydra:member": [{
		"@id": "https://data.delijn.be/stops/204291",
		"http://xmlns.com/foaf/0.1/name": [{
			"@value": "Trinity Street"
		}],
                "http://purl.org/dc/terms/description": "This street was the first in many in an effort to start a city."
	}],

	"hydra:totalItems": 164,
	"@id": "/stops/fragment1.jsonld#806"
}
```
In the example above tree:value is the "T" start of the name of the street as well as the start of the description. The tree:value could even not be related with any data in the hydra:members at all and could be some higher abstraction.

The content of this tree:value is dependent on the tree:childRelation between the parent node and the node owning the value (e.g. string, number, coordinate, etc). But there is no definition on how the tree:value should be linked to the members of the node owning the value. 

I suggest one of two things: 

1. Each tree:childRelation is associated with a certain relation type (e.g. tree:stringCompletes with dcterms:title, rdfs:label or foaf:name).
2. Altering the tree ontology syntax so that when describing a node, we also describe what relation the tree:value wil have towards the hydra:members. For example:

```
{
        "@type": "tree:Node",
        "tree:value": "T",
        "tree:valueRelatesTo": "foaf:name",

	...
}
```

**Comment by pietercolpaert** [comment]
Being tackled in the new spec with shacl:path and hydra:manages on the collection
